replicaCount: 1

image_cast:
  repository: lngd/api-cast
  tag: v.42.0

image_movie:
  repository: lngd/api-movie
  tag: latest

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true # ou false en fonction de vos besoins
  hosts:
    - host: service
      paths:
        - path: /api/v1/casts
  tls: false
