apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.deployment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: {{ .Values.image.name }}
        # - name: "test"
          securityContext:
          securityContext:
          # image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          image: "{{ .Values.image.test }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: {{ .Values.db.password }}
            - name: POSTGRES_USER
              valueFrom:
              value: {{ .Values.db.user }}
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
            - name: DATABASE_URI
              value: {{ .Values.service.databaseUri }}
            - name: {{ .Values.service.name_cast }}
              value: {{ .Values.service.castServiceHostUrl }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountpath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.volume.name }} # Nom du volume pour le stockage des données persistantes
          persistentVolumeClaim:
            claimName: {{ include "api.fullname" . }}
