apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api.fullname" $ }}
  labels:
    app: api
spec:
  ingressClassName: traefik-int
  rules:
    - host: {{ .Values.service.name }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
