apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: api
    tier: postgress
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      protocol: TCP
  selector:
    app: api
    tier: postgress