apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api
      tier: postgress
  template:
    metadata:
      labels:
        app: api
        tier: postgress
    spec:
      containers:
        - name: {{ .Values.db.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "postgres:12.1-alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: {{ .Values.db.password }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
            - name: DATABASE_URI
              value: {{ .Values.service.databaseUri }}
            - name: {{ .Values.service.name_cast }}
              value: {{ .Values.service.castServiceHostUrl }}
          ports:
            - name: http
              containerPort: {{ .Values.db.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: /var/lib/postgresql/data/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.volume.name }} # Nom du volume pour le stockage des données persistantes
          persistentVolumeClaim:
            claimName: {{ include "api.fullname" . }}

