apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      tier: postgress
  template:
    metadata:
      labels:
        app: api
        tier: postgress
    spec:
      containers:
        - name: cast-db
          image: "postgres:12.1-alpine"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: cast-password
            - name: POSTGRES_USER
              value: cast-user
            - name: POSTGRES_DB
              value: cast-db
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
            - name: MOVIE_SERVICE_HOST_URL
              value: http://movie-service:8001/api/v1/movie
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          volumeMounts:
            - name: postgres-data-cast
              mountPath: /var/lib/postgresql/data/
      volumes:
        - name: postgres-data-cast # Nom du volume pour le stockage des données persistantes
          persistentVolumeClaim:
            claimName: pvc-jenkins

