apiVersion: v1
kind: Service
metadata:
  name: cast_db
  labels:
    app: api
    tier: postgress
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: api
    tier: postgress
