apiVersion: v1
kind: Service
metadata:
  name: cast-service
  labels: 
    app: api
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: api
