apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-jenkins
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: api
 minReplicas: 3
 maxReplicas: 6
 targetCPUUtilizationPercentage: 70
