apiVersion: v1
kind: Service
metadata:
  name: movie-service
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: api