apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: movie
          securityContext:
          securityContext:
          image: "{{ .Values.image_movie.repository }}:{{ .Values.image_movie.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: movie-password
            - name: POSTGRES_USER
              valueFrom:
              value: movie-user
            - name: POSTGRES_DB
              value: movie-db
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
            - name: CAST_SERVICE_HOST_URL
              value: http://cast-service:8002/api/v1/casts
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: movie-data
              mountPath: /app
      volumes:
        - name: movie-data # Nom du volume pour le stockage des données persistantes
          persistentVolumeClaim:
            claimName: pvc-jenkins
