apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: api
    tier: nginx
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api
    tier: nginx
