apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
  labels:
    app: api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi